version: '3.8'

services:
  app:
    build: .
    container_name: blog_api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_NAME=blog_api_dev
      - JWT_SECRET=supersecretkey123
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: blog_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_api_dev
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
